DB_PATH = './resource/database.db'

CREATE_STUDENT_INFO_COMMAND = '1'
PRINT_STUDENT_INFO_COMMAND = '2'
CREATE_STUDENT_COMMAND = '3'
PRINT_STUDENT_COMMAND = '4'
UPDATE_STUDENT_COMMAND = '5'
DELETE_STUDENT_COMMAND = '6'


IS_GRADE_FALSE = '미입력'
IS_GRADE_TRUE = '입력'
